package io.github.ghals5737.loadmin.core.export;

import java.util.ArrayList;
import java.util.EnumSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.StringJoiner;

import io.github.ghals5737.loadmin.core.engine.LoadTestSpec;
import io.github.ghals5737.loadmin.core.template.ValueTemplate;
import io.github.ghals5737.loadmin.core.template.ValueTemplate.Kind;
import io.github.ghals5737.loadmin.core.template.ValueTemplate.Literal;
import io.github.ghals5737.loadmin.core.template.ValueTemplate.Part;
import io.github.ghals5737.loadmin.core.template.ValueTemplate.Placeholder;

/**
 * Writes a single Gatling simulation in the Java DSL.
 *
 * <p>Gatling runs its virtual users in one JVM, so every generator keeps the
 * meaning it has in loadmin — {@code ${seq}} included, as one shared counter.
 * The injection profile is closed (a fixed number of concurrent users), which
 * is how the built-in engine behaves too.
 */
public class GatlingScriptExporter implements ScriptExporter {

    private static final String CLASS_NAME = "LoadminSimulation";
    /** Beyond this many choices the values get their own field. */
    private static final int INLINE_VALUES = 5;

    @Override
    public String id() {
        return "gatling";
    }

    @Override
    public String fileName(ExportRequest request) {
        return CLASS_NAME + ".java";
    }

    @Override
    public String render(ExportRequest request) {
        LoadTestSpec spec = request.spec();
        Set<Kind> used = EnumSet.noneOf(Kind.class);
        List<String[]> counters = new ArrayList<>();
        List<String[]> steps = new ArrayList<>();
        for (LoadTestSpec.Step step : spec.steps()) {
            ValueTemplate path = ValueTemplate.compile(
                    step.pathTemplate(), ValueTemplate.Mode.PATH, request.valueLists());
            boolean hasBody = step.bodyTemplate() != null && !step.bodyTemplate().isBlank();
            ValueTemplate body = hasBody
                    ? ValueTemplate.compile(
                            step.bodyTemplate(), ValueTemplate.Mode.BODY, request.valueLists())
                    : null;
            steps.add(new String[] {
                    step.name(),
                    step.httpMethod().toLowerCase(),
                    expression(path, used, counters),
                    body == null ? null : expression(body, used, counters) });
        }
        String label = spec.label();
        Map<String, String> headers = request.headers();

        StringBuilder out = new StringBuilder();
        headers.keySet().stream().filter(ExportRequest::secret).forEach(name ->
                out.append("// ").append(name).append(" is read from a system property, not stored here:\n")
                        .append("//   -D").append(ExportRequest.variable(name).toLowerCase())
                        .append("=...\n"));
        out.append("// Generated by loadmin — ").append(label).append("\n//\n")
                .append("// A single Gatling simulation. Drop it into a Gatling project's\n")
                .append("// src/test/java and run it:\n")
                .append("//   ./gradlew gatlingRun -DbaseUrl=").append(request.baseUrl()).append("\n//\n")
                .append("// The load now comes from another process, so it no longer competes with\n")
                .append("// the application for CPU, threads and GC. Keep /loadmin open while it runs\n")
                .append("// to watch what the server does internally.\n\n")
                .append("import static io.gatling.javaapi.core.CoreDsl.*;\n")
                .append("import static io.gatling.javaapi.http.HttpDsl.*;\n\n");
        if (used.contains(Kind.UUID)) {
            out.append("import java.util.UUID;\n");
        }
        if (used.contains(Kind.INT) || used.contains(Kind.ALPHA) || used.contains(Kind.PICK)) {
            out.append("import java.util.concurrent.ThreadLocalRandom;\n");
        }
        if (counters.stream().anyMatch(c -> c[0].startsWith("VALUES_"))) {
            out.append("import java.util.List;\n");
        }
        if (counters.stream().anyMatch(c -> !c[0].startsWith("VALUES_"))) {
            out.append("import java.util.concurrent.atomic.AtomicLong;\n");
        }
        out.append("\nimport io.gatling.javaapi.core.ScenarioBuilder;\n")
                .append("import io.gatling.javaapi.core.Simulation;\n")
                .append("import io.gatling.javaapi.http.HttpProtocolBuilder;\n\n")
                .append("public class ").append(CLASS_NAME).append(" extends Simulation {\n\n");

        for (String[] counter : counters) {
            if (counter[0].startsWith("VALUES_")) {
                out.append("    private static final List<String> ").append(counter[0])
                        .append(" = ").append(counter[1]).append(";\n");
            } else {
                out.append("    private static final AtomicLong ").append(counter[0])
                        .append(" = new AtomicLong(").append(counter[1]).append("L);\n");
            }
        }
        if (!counters.isEmpty()) {
            out.append('\n');
        }

        appendHelpers(out, used);

        out.append("    private final HttpProtocolBuilder httpProtocol = http\n")
                .append("            .baseUrl(System.getProperty(\"baseUrl\", \"")
                .append(java(request.baseUrl())).append("\"))");
        headers.forEach((name, value) -> out.append("\n            .header(\"").append(java(name))
                .append("\", ").append(ExportRequest.secret(name)
                        ? "System.getProperty(\"" + ExportRequest.variable(name).toLowerCase()
                                + "\", \"\")"
                        : "\"" + java(value) + "\"")
                .append(")"));
        out.append(";\n\n")
                .append("    private final ScenarioBuilder scn = scenario(\"").append(java(label))
                .append("\")");
        for (String[] step : steps) {
            out.append("\n            .exec(http(\"").append(java(step[0])).append("\")\n")
                    .append("                    .").append(step[1])
                    .append("(session -> ").append(step[2]).append(")\n");
            if (step[3] != null) {
                out.append("                    .header(\"Content-Type\", \"application/json\")\n")
                        .append("                    .body(StringBody(session -> ").append(step[3])
                        .append("))\n");
            }
            out.append("                    .check(status().lt(400)))");
        }
        out.append(";\n\n")
                .append("    {\n")
                .append("        setUp(scn.injectClosed(constantConcurrentUsers(")
                .append(spec.concurrency()).append(").during(")
                .append(spec.durationSeconds()).append(")))\n")
                .append("                .protocols(httpProtocol);\n")
                .append("    }\n}\n");
        return out.toString();
    }

    private String expression(ValueTemplate template, Set<Kind> used, List<String[]> counters) {
        if (!template.dynamic()) {
            return "\"" + java(template.source()) + "\"";
        }
        StringJoiner joiner = new StringJoiner(" + ");
        for (Part part : template.parts()) {
            if (part instanceof Literal literal) {
                joiner.add("\"" + java(literal.text()) + "\"");
                continue;
            }
            Placeholder placeholder = (Placeholder) part;
            used.add(placeholder.kind());
            List<String> args = placeholder.args();
            switch (placeholder.kind()) {
                // nextLong's upper bound is exclusive; loadmin's is inclusive.
                case INT -> joiner.add("ThreadLocalRandom.current().nextLong(" + args.get(0) + "L, "
                        + (Long.parseLong(args.get(1)) + 1) + "L)");
                case UUID -> joiner.add("UUID.randomUUID()");
                case NOW -> joiner.add("System.currentTimeMillis()");
                case ALPHA -> joiner.add("randomAlpha(" + args.get(0) + ")");
                case PICK -> joiner.add(args.size() > INLINE_VALUES
                        ? "pick(" + hoist(counters, args) + ")"
                        : "pick(" + javaList(args) + ")");
                case ROTATE -> {
                    String values = hoist(counters, args);
                    String variable = "CYCLE_" + (counters.size() + 1);
                    counters.add(new String[] { variable, "0" });
                    joiner.add(values + ".get((int) Math.floorMod(" + variable
                            + ".getAndIncrement(), " + values + ".size()))");
                }
                case SEQ -> {
                    String variable = "SEQ_" + (counters.size() + 1);
                    counters.add(new String[] { variable, args.get(0) });
                    joiner.add(variable + ".getAndIncrement()");
                }
                case CYCLE -> {
                    String variable = "CYCLE_" + (counters.size() + 1);
                    long min = Long.parseLong(args.get(0));
                    long size = Long.parseLong(args.get(1)) - min + 1;
                    counters.add(new String[] { variable, "0" });
                    joiner.add("(" + min + "L + " + variable + ".getAndIncrement() % " + size + "L)");
                }
                default -> throw new IllegalStateException("unhandled generator " + placeholder.kind());
            }
        }
        // A leading String literal keeps the whole concatenation a String.
        String expression = joiner.toString();
        return expression.startsWith("\"") ? expression : "\"\" + " + expression;
    }

    private static void appendHelpers(StringBuilder out, Set<Kind> used) {
        if (used.contains(Kind.ALPHA)) {
            out.append("    private static String randomAlpha(int length) {\n")
                    .append("        String chars = \"abcdefghijklmnopqrstuvwxyz0123456789\";\n")
                    .append("        StringBuilder value = new StringBuilder(length);\n")
                    .append("        for (int i = 0; i < length; i++) {\n")
                    .append("            value.append(chars.charAt(ThreadLocalRandom.current().nextInt(chars.length())));\n")
                    .append("        }\n        return value.toString();\n    }\n\n");
        }
        if (used.contains(Kind.PICK)) {
            out.append("    private static String pick(String... values) {\n")
                    .append("        return values[ThreadLocalRandom.current().nextInt(values.length)];\n")
                    .append("    }\n\n");
        }
    }

    /** Lifts a long list of values out of the request into a field. */
    private static String hoist(List<String[]> counters, List<String> values) {
        String variable = "VALUES_" + (counters.size() + 1);
        counters.add(new String[] { variable, "List.of(" + javaList(values) + ")" });
        return variable;
    }

    private static String javaList(List<String> values) {
        StringJoiner joiner = new StringJoiner(", ");
        values.forEach(value -> joiner.add("\"" + java(value) + "\""));
        return joiner.toString();
    }

    /** Escapes a value for a Java string literal. */
    private static String java(String value) {
        return value.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r");
    }
}
