package io.github.ghals5737.loadmin.core.export;

import java.util.ArrayList;
import java.util.EnumSet;
import java.util.List;
import java.util.Set;
import java.util.StringJoiner;

import io.github.ghals5737.loadmin.core.template.ValueTemplate;
import io.github.ghals5737.loadmin.core.template.ValueTemplate.Kind;
import io.github.ghals5737.loadmin.core.template.ValueTemplate.Literal;
import io.github.ghals5737.loadmin.core.template.ValueTemplate.Part;
import io.github.ghals5737.loadmin.core.template.ValueTemplate.Placeholder;

/**
 * Writes a self-contained k6 script: no imports from jslib, so it runs offline
 * with nothing but k6 itself.
 *
 * <p>One generator does not survive the trip unchanged. k6 gives every virtual
 * user its own JS runtime, so {@code ${seq}} cannot be a single shared counter;
 * each user gets its own, started far enough apart that values stay distinct.
 * The generated script says so in a comment.
 */
public class K6ScriptExporter implements ScriptExporter {

    private static final long SEQ_STRIDE_PER_VU = 1_000_000L;

    @Override
    public String id() {
        return "k6";
    }

    @Override
    public String fileName(ExportRequest request) {
        return "loadmin-" + ScriptExporter.slug(request.pathPattern()) + ".js";
    }

    @Override
    public String render(ExportRequest request) {
        ValueTemplate path = ValueTemplate.compile(request.pathTemplate(), ValueTemplate.Mode.PATH);
        boolean hasBody = request.bodyTemplate() != null && !request.bodyTemplate().isBlank();
        ValueTemplate body = hasBody
                ? ValueTemplate.compile(request.bodyTemplate(), ValueTemplate.Mode.BODY)
                : null;

        Set<Kind> used = EnumSet.noneOf(Kind.class);
        List<String> sequences = new ArrayList<>();
        String pathExpression = expression(path, used, sequences);
        String bodyExpression = body == null ? null : expression(body, used, sequences);

        StringBuilder out = new StringBuilder();
        out.append("// Generated by loadmin — ").append(request.httpMethod()).append(' ')
                .append(request.pathPattern()).append("\n//\n")
                .append("// Run it from outside the application under test:\n")
                .append("//   BASE_URL=").append(request.baseUrl()).append(" k6 run ")
                .append(fileName(request)).append("\n//\n")
                .append("// The load now comes from another process, so it no longer competes with\n")
                .append("// the application for CPU, threads and GC. Keep /loadmin open while it runs\n")
                .append("// to watch what the server does internally.\n");
        if (!sequences.isEmpty()) {
            out.append("//\n")
                    .append("// Note: k6 runs every virtual user in its own JS runtime, so ${seq} cannot\n")
                    .append("// be one shared counter. Each user counts on its own, started ")
                    .append(SEQ_STRIDE_PER_VU).append(" apart.\n");
        }
        out.append("\nimport http from 'k6/http';\n")
                .append("import { check } from 'k6';\n\n")
                .append("export const options = {\n")
                .append("  vus: ").append(request.concurrency()).append(",\n")
                .append("  duration: '").append(request.durationSeconds()).append("s',\n")
                .append("};\n\n")
                .append("const BASE_URL = __ENV.BASE_URL || '").append(js(request.baseUrl())).append("';\n");

        appendHelpers(out, used);

        for (String sequence : sequences) {
            out.append("\nlet ").append(sequence).append(" = ").append(sequenceStart(sequence)).append(";\n");
        }

        out.append("\nexport default function () {\n")
                .append("  const url = BASE_URL + ").append(pathExpression).append(";\n");
        if (bodyExpression != null) {
            out.append("  const body = ").append(bodyExpression).append(";\n")
                    .append("  const params = { headers: { 'Content-Type': 'application/json' } };\n")
                    .append("  const res = http.request('").append(request.httpMethod())
                    .append("', url, body, params);\n");
        } else {
            out.append("  const res = http.request('").append(request.httpMethod())
                    .append("', url);\n");
        }
        out.append("  check(res, { 'status is 2xx': (r) => r.status >= 200 && r.status < 300 });\n")
                .append("}\n");
        return out.toString();
    }

    /** The sequence variable carries its start value in its name suffix. */
    private static String sequenceStart(String variable) {
        String start = variable.substring(variable.lastIndexOf('_') + 1);
        return start + " + (__VU - 1) * " + SEQ_STRIDE_PER_VU;
    }

    private String expression(ValueTemplate template, Set<Kind> used, List<String> sequences) {
        if (!template.dynamic()) {
            return "'" + js(template.source()) + "'";
        }
        StringJoiner joiner = new StringJoiner(" + ");
        for (Part part : template.parts()) {
            if (part instanceof Literal literal) {
                joiner.add("'" + js(literal.text()) + "'");
                continue;
            }
            Placeholder placeholder = (Placeholder) part;
            used.add(placeholder.kind());
            List<String> args = placeholder.args();
            switch (placeholder.kind()) {
                case INT -> joiner.add("randomInt(" + args.get(0) + ", " + args.get(1) + ")");
                case UUID -> joiner.add("uuid()");
                case NOW -> joiner.add("Date.now()");
                case ALPHA -> joiner.add("randomAlpha(" + args.get(0) + ")");
                case PICK -> joiner.add("pick([" + jsList(args) + "])");
                case SEQ -> {
                    String variable = "seq_" + (sequences.size() + 1) + "_" + args.get(0);
                    sequences.add(variable);
                    joiner.add(variable + "++");
                }
                default -> throw new IllegalStateException("unhandled generator " + placeholder.kind());
            }
        }
        return joiner.toString();
    }

    private static void appendHelpers(StringBuilder out, Set<Kind> used) {
        if (used.contains(Kind.INT)) {
            out.append("\nfunction randomInt(min, max) {\n")
                    .append("  return Math.floor(Math.random() * (max - min + 1)) + min;\n}\n");
        }
        if (used.contains(Kind.ALPHA)) {
            out.append("\nfunction randomAlpha(length) {\n")
                    .append("  const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';\n")
                    .append("  let value = '';\n")
                    .append("  for (let i = 0; i < length; i++) {\n")
                    .append("    value += chars[Math.floor(Math.random() * chars.length)];\n")
                    .append("  }\n  return value;\n}\n");
        }
        if (used.contains(Kind.UUID)) {
            out.append("\nfunction uuid() {\n")
                    .append("  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {\n")
                    .append("    const r = (Math.random() * 16) | 0;\n")
                    .append("    return (c === 'x' ? r : (r & 0x3) | 0x8).toString(16);\n")
                    .append("  });\n}\n");
        }
        if (used.contains(Kind.PICK)) {
            out.append("\nfunction pick(values) {\n")
                    .append("  return values[Math.floor(Math.random() * values.length)];\n}\n");
        }
    }

    private static String jsList(List<String> values) {
        StringJoiner joiner = new StringJoiner(", ");
        values.forEach(value -> joiner.add("'" + js(value) + "'"));
        return joiner.toString();
    }

    /** Escapes a value for a single-quoted JavaScript string literal. */
    private static String js(String value) {
        return value.replace("\\", "\\\\")
                .replace("'", "\\'")
                .replace("\n", "\\n")
                .replace("\r", "\\r");
    }
}
