package io.github.ghals5737.loadmin.core.export;

import java.util.ArrayList;
import java.util.EnumSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.StringJoiner;

import io.github.ghals5737.loadmin.core.engine.LoadTestSpec;
import io.github.ghals5737.loadmin.core.template.ValueTemplate;
import io.github.ghals5737.loadmin.core.template.ValueTemplate.Kind;
import io.github.ghals5737.loadmin.core.template.ValueTemplate.Literal;
import io.github.ghals5737.loadmin.core.template.ValueTemplate.Part;
import io.github.ghals5737.loadmin.core.template.ValueTemplate.Placeholder;

/**
 * Writes a self-contained k6 script: no imports from jslib, so it runs offline
 * with nothing but k6 itself.
 *
 * <p>One generator does not survive the trip unchanged. k6 gives every virtual
 * user its own JS runtime, so {@code ${seq}} cannot be a single shared counter;
 * each user gets its own, started far enough apart that values stay distinct.
 * The generated script says so in a comment.
 */
public class K6ScriptExporter implements ScriptExporter {

    private static final long SEQ_STRIDE_PER_VU = 1_000_000L;

    @Override
    public String id() {
        return "k6";
    }

    @Override
    public String fileName(ExportRequest request) {
        return "loadmin-" + ScriptExporter.stem(request) + ".js";
    }

    @Override
    public String render(ExportRequest request) {
        LoadTestSpec spec = request.spec();
        Set<Kind> used = EnumSet.noneOf(Kind.class);
        List<String[]> counters = new ArrayList<>();
        List<String[]> steps = new ArrayList<>();
        for (LoadTestSpec.Step step : spec.steps()) {
            ValueTemplate path = ValueTemplate.compile(step.pathTemplate(), ValueTemplate.Mode.PATH);
            boolean hasBody = step.bodyTemplate() != null && !step.bodyTemplate().isBlank();
            ValueTemplate body = hasBody
                    ? ValueTemplate.compile(step.bodyTemplate(), ValueTemplate.Mode.BODY)
                    : null;
            steps.add(new String[] {
                    step.name(),
                    step.httpMethod(),
                    expression(path, used, counters),
                    body == null ? null : expression(body, used, counters) });
        }
        boolean scenario = steps.size() > 1;
        Map<String, String> headers = request.headers();

        StringBuilder out = new StringBuilder();
        out.append("// Generated by loadmin — ").append(spec.label()).append("\n//\n")
                .append("// Run it from outside the application under test:\n")
                .append("//   BASE_URL=").append(request.baseUrl()).append(" k6 run ")
                .append(fileName(request)).append("\n//\n")
                .append("// The load now comes from another process, so it no longer competes with\n")
                .append("// the application for CPU, threads and GC. Keep /loadmin open while it runs\n")
                .append("// to watch what the server does internally.\n");
        if (!counters.isEmpty()) {
            out.append("//\n")
                    .append("// Note: k6 runs every virtual user in its own JS runtime, so a counter\n")
                    .append("// cannot be shared. Each user counts on its own — ${seq} values are kept\n")
                    .append("// ").append(SEQ_STRIDE_PER_VU)
                    .append(" apart so they stay distinct, and ${cycle} walks its range per user.\n");
        }
        headers.keySet().stream().filter(ExportRequest::secret).forEach(name ->
                out.append("//\n// ").append(name).append(" is read from the environment, not stored here:\n")
                        .append("//   ").append(ExportRequest.variable(name)).append("=... k6 run ")
                        .append(fileName(request)).append('\n'));
        out.append("\nimport http from 'k6/http';\n")
                .append(scenario ? "import { check, group } from 'k6';\n\n" : "import { check } from 'k6';\n\n")
                .append("export const options = {\n")
                .append("  vus: ").append(spec.concurrency()).append(",\n")
                .append("  duration: '").append(spec.durationSeconds()).append("s',\n")
                .append("};\n\n")
                .append("const BASE_URL = __ENV.BASE_URL || '").append(js(request.baseUrl())).append("';\n");

        if (!headers.isEmpty()) {
            out.append("\nconst HEADERS = {\n");
            headers.forEach((name, value) -> out.append("  '").append(js(name)).append("': ")
                    .append(ExportRequest.secret(name)
                            ? "__ENV." + ExportRequest.variable(name) + " || ''"
                            : "'" + js(value) + "'")
                    .append(",\n"));
            out.append("};\n");
        }

        appendHelpers(out, used);

        for (String[] counter : counters) {
            out.append("\nlet ").append(counter[0]).append(" = ").append(counter[1]).append(";\n");
        }

        out.append("\nexport default function () {\n");
        for (String[] step : steps) {
            String indent = scenario ? "    " : "  ";
            if (scenario) {
                out.append("  group('").append(js(step[0])).append("', () => {\n");
            }
            out.append(indent).append("const url = BASE_URL + ").append(step[2]).append(";\n");
            String jsonHeader = headers.isEmpty()
                    ? "{ 'Content-Type': 'application/json' }"
                    : "{ ...HEADERS, 'Content-Type': 'application/json' }";
            if (step[3] != null) {
                out.append(indent).append("const body = ").append(step[3]).append(";\n")
                        .append(indent).append("const params = { headers: ").append(jsonHeader).append(" };\n")
                        .append(indent).append("const res = http.request('").append(step[1])
                        .append("', url, body, params);\n");
            } else if (!headers.isEmpty()) {
                out.append(indent).append("const res = http.request('").append(step[1])
                        .append("', url, null, { headers: HEADERS });\n");
            } else {
                out.append(indent).append("const res = http.request('").append(step[1])
                        .append("', url);\n");
            }
            out.append(indent)
                    .append("check(res, { 'status is 2xx': (r) => r.status >= 200 && r.status < 300 });\n");
            if (scenario) {
                out.append("  });\n");
            }
        }
        out.append("}\n");
        return out.toString();
    }

    private String expression(ValueTemplate template, Set<Kind> used, List<String[]> counters) {
        if (!template.dynamic()) {
            return "'" + js(template.source()) + "'";
        }
        StringJoiner joiner = new StringJoiner(" + ");
        for (Part part : template.parts()) {
            if (part instanceof Literal literal) {
                joiner.add("'" + js(literal.text()) + "'");
                continue;
            }
            Placeholder placeholder = (Placeholder) part;
            used.add(placeholder.kind());
            List<String> args = placeholder.args();
            switch (placeholder.kind()) {
                case INT -> joiner.add("randomInt(" + args.get(0) + ", " + args.get(1) + ")");
                case UUID -> joiner.add("uuid()");
                case NOW -> joiner.add("Date.now()");
                case ALPHA -> joiner.add("randomAlpha(" + args.get(0) + ")");
                case PICK -> joiner.add("pick([" + jsList(args) + "])");
                case SEQ -> {
                    String variable = "seq_" + (counters.size() + 1);
                    counters.add(new String[] {
                            variable, args.get(0) + " + (__VU - 1) * " + SEQ_STRIDE_PER_VU });
                    joiner.add(variable + "++");
                }
                case CYCLE -> {
                    String variable = "cycle_" + (counters.size() + 1);
                    long min = Long.parseLong(args.get(0));
                    long size = Long.parseLong(args.get(1)) - min + 1;
                    counters.add(new String[] { variable, "0" });
                    joiner.add("(" + min + " + " + variable + "++ % " + size + ")");
                }
                default -> throw new IllegalStateException("unhandled generator " + placeholder.kind());
            }
        }
        return joiner.toString();
    }

    private static void appendHelpers(StringBuilder out, Set<Kind> used) {
        if (used.contains(Kind.INT)) {
            out.append("\nfunction randomInt(min, max) {\n")
                    .append("  return Math.floor(Math.random() * (max - min + 1)) + min;\n}\n");
        }
        if (used.contains(Kind.ALPHA)) {
            out.append("\nfunction randomAlpha(length) {\n")
                    .append("  const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';\n")
                    .append("  let value = '';\n")
                    .append("  for (let i = 0; i < length; i++) {\n")
                    .append("    value += chars[Math.floor(Math.random() * chars.length)];\n")
                    .append("  }\n  return value;\n}\n");
        }
        if (used.contains(Kind.UUID)) {
            out.append("\nfunction uuid() {\n")
                    .append("  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {\n")
                    .append("    const r = (Math.random() * 16) | 0;\n")
                    .append("    return (c === 'x' ? r : (r & 0x3) | 0x8).toString(16);\n")
                    .append("  });\n}\n");
        }
        if (used.contains(Kind.PICK)) {
            out.append("\nfunction pick(values) {\n")
                    .append("  return values[Math.floor(Math.random() * values.length)];\n}\n");
        }
    }

    private static String jsList(List<String> values) {
        StringJoiner joiner = new StringJoiner(", ");
        values.forEach(value -> joiner.add("'" + js(value) + "'"));
        return joiner.toString();
    }

    /** Escapes a value for a single-quoted JavaScript string literal. */
    private static String js(String value) {
        return value.replace("\\", "\\\\")
                .replace("'", "\\'")
                .replace("\n", "\\n")
                .replace("\r", "\\r");
    }
}
